### ISSUE TITLE
PHP Fatal error:  Uncaught Error: Cannot use object of type WP_Error as array in class-newspack-popups-data-api.php:120

### ISSUE THREAD

**Issue by yogeshbeniwal** [Automattic/newspack-popups#1206]
Upgrade to v2.22.0 is resulting into below error

`
2023/08/22 14:20:53 [error] 13835#13835: *5449 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Cannot use object of type WP_Error as array in /newspack-popups/includes/class-newspack-popups-data-api.php:120
Stack trace:
#0 /newspack-popups/includes/class-newspack-popups-data-api.php(165): Newspack_Popups_Data_Api::get_popup_metadata()
#1 /wp-includes/class-wp-hook.php(310): Newspack_Popups_Data_Api::get_rendered_popups()
#2 /wp-includes/class-wp-hook.php(334): WP_Hook->apply_filters()
#3 /wp-includes/plugin.php(517): WP_Hook->do_action()
#4 /newspack-popups/includes/class-newspack-popups-model.php(1135): do_action()
#5 /newspack-popups/includes/class-newspack-popups-inserter.php(532): Newspack_Popups_Model::generate_popup()
`

**Comment by miguelpeixe** [comment]
It looks like this may happen if the reader revenue settings fail to return a valid configuration array. Do you have properly configured donation settings and products with WC?

I'll look into handling this error so it doesn't throw a fatal.
