### ISSUE TITLE
Breaks Liveblog editor even when campaigns are disabled

### ISSUE THREAD

**Issue by philipjohn** [Automattic/newspack-popups#299]
**Describe the bug**
When active, the Campaigns plugin breaks formatting in the Liveblog editor as well as deleting text. It makes editing a liveblog extremely hard. This is a problem even if Campaigns are disabled on the liveblog post _and_ even if there are no campaigns created (draft or otherwise).

**To Reproduce**
1. On a test site, ensure Liveblog is installed and create a new post enabling liveblog on it. Turn AMP off for the post.
2. Visit the liveblog to see the editor - enter some text and use backspace/delete as well as the formatting tools. They should work fine.
3. Activate Newspack Campaigns
4. Repeat step 2 after refreshing and you should find formatting is broken. Behaviour should match the video below.

**Screenshots**
Here's a video: https://cloudup.com/clT9XZ2Dgjy

**Expected behavior**
Campaigns should not be affecting the Liveblog editor, which should still function as normal.

**Comment by philipjohn** [comment]
Some more info... I'm seeing this error in the console:

```
Uncaught TypeError: Cannot read property 'getElementsByTagName' of null
    at eval (amp-fallback.js:10)
    at eval (amp-fallback.js:174)
    at Object../newspack-theme/js/src/amp-fallback.js (amp-fallback.js?ver=1.21.0:96)
    at __webpack_require__ (amp-fallback.js?ver=1.21.0:20)
    at amp-fallback.js?ver=1.21.0:84
    at amp-fallback.js?ver=1.21.0:87
```

I also see this, even though AMP and Campaigns are both disabled for the post:

> Powered by AMP ⚡ HTML – Version 2010132225003 http://one.wordpress.test/liveblog/

**Comment by philipjohn** [comment]
The 'amp-fallback' error is unrelated. It was from the theme and caused by no primary menu being selected.

**Comment by philipjohn** [comment]
This console error is relevant though, as it appears any time you interact with the Liveblog editor.:

```
Uncaught Invariant Violation: editorNode.firstChild is not an HTMLElement
    at invariant (http://one.wordpress.test/wp-content/plugins/liveblog/assets/0.bundle.js:5671:15)
    at editOnSelect (http://one.wordpress.test/wp-content/plugins/liveblog/assets/0.bundle.js:88505:61)
    at http://one.wordpress.test/wp-content/plugins/liveblog/assets/0.bundle.js:82481:19
    at HTMLUnknownElement.callCallback (http://one.wordpress.test/wp-content/plugins/liveblog/assets/app.js?ver=1.9.5:9013:14)
    at Object.invokeGuardedCallbackDev (http://one.wordpress.test/wp-content/plugins/liveblog/assets/app.js?ver=1.9.5:9062:16)
    at invokeGuardedCallback (http://one.wordpress.test/wp-content/plugins/liveblog/assets/app.js?ver=1.9.5:9117:31)
    at invokeGuardedCallbackAndCatchFirstError (http://one.wordpress.test/wp-content/plugins/liveblog/assets/app.js?ver=1.9.5:9131:25)
    at executeDispatch (http://one.wordpress.test/wp-content/plugins/liveblog/assets/app.js?ver=1.9.5:9214:3)
    at executeDispatchesInOrder (http://one.wordpress.test/wp-content/plugins/liveblog/assets/app.js?ver=1.9.5:9239:5)
    at executeDispatchesAndRelease (http://one.wordpress.test/wp-content/plugins/liveblog/assets/app.js?ver=1.9.5:12103:5)
```

Liveblogs don't need any post_content, because the Liveblog gets inserted. I tried adding a simple paragraph in though (which then just appears above the Liveblog) to see if Campaigns was tripping things up given the `firstChild` in the error, but it had no effect.

My guess is that campaigns, despite being turned off and there being no campaigns, is still loading _something_ and that's interfering with either the DOM or Liveblog's JS and making it fail.
